name: CI/CD Deploy to Timeweb via SSH with Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Copy Ansible playbook to server via sshpass
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no ansible/playbook.yml ${{ secrets.USER }}@${{ secrets.HOST }}:/home/c/co71624/playbook.yml

    - name: Run Ansible playbook on server via sshpass
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook ~/playbook.yml -i localhost,
        EOF

