name: CI/CD for Go App with Ansible

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check environment variables
      run: |
        echo "Host: ${{ secrets.HOST }}"
        echo "User: ${{ secrets.USER }}"

    - name: Copy Ansible playbook to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "/Ansible/"  # Убедитесь, что путь правильный
        target: "~/playbook.yml"



    - name: Check if playbook was copied
      run: |
        ls -l ~/playbook.yml  # Проверим, что файл на сервере

    - name: Install Ansible and run playbook
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook ~/playbook.yml -i, --connection=local

